/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.43).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ordermng.api;

import com.ordermng.api.model.ItemRequest;
import com.ordermng.api.model.Result;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-07-23T12:06:14.117462+01:00[Europe/Lisbon]")
@Validated
public interface ItemApi {

    @Operation(summary = "Add a new item to the store", description = "Add a new item to the store", tags={ "item" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/item",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Result> addItem(@Parameter(in = ParameterIn.DEFAULT, description = "Create a new item in the store", required=true, schema=@Schema()) @Valid @RequestBody ItemRequest body);


    @Operation(summary = "Delete an item", description = "delete an item", tags={ "item" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid pet value") })
    @RequestMapping(value = "/item",
        method = RequestMethod.DELETE)
    ResponseEntity<Result> deleteItem(@Parameter(in = ParameterIn.HEADER, description = "Item code to delete" ,required=true,schema=@Schema()) @RequestHeader(value="code", required=true) String code);


    @Operation(summary = "List items", description = "List all items available", tags={ "item" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ItemApi.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/item",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Result> listItems();


    @Operation(summary = "Update an existing item", description = "Update an existing item by Id", tags={ "item" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Item not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation exception") })
    @RequestMapping(value = "/item",
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Result> updateItem(@Parameter(in = ParameterIn.DEFAULT, description = "Update an existent item in the store", required=true, schema=@Schema()) @Valid @RequestBody ItemRequest body);
}

