/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.43).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ordermng.api;

import com.ordermng.api.model.StockMoviment;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-07-07T11:52:41.130101+01:00[Europe/Lisbon]")
@Validated
public interface MovimentApi {

    @Operation(summary = "Add a new stock moviment to the store", description = "Add a new stock moviment to the store", tags={ "moviment" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = StockMoviment.class))),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/moviment",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<StockMoviment> addStockMoviment(@Parameter(in = ParameterIn.DEFAULT, description = "Create a new stock moviment in the store", required=true, schema=@Schema()) @Valid @RequestBody StockMoviment body);


    @Operation(summary = "Delete an stock moviment", description = "delete an stock moviment", tags={ "moviment" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "400", description = "Invalid pet value") })
    @RequestMapping(value = "/moviment",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteStockMoviment(@Parameter(in = ParameterIn.HEADER, description = "Stock moviment id to delete" ,required=true,schema=@Schema()) @RequestHeader(value="id", required=true) Long id);


    @Operation(summary = "List stock moviment", description = "List all stock moviment available", tags={ "moviment" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = StockMoviment.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/moviment",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<StockMoviment>> listStockMoviment();


    @Operation(summary = "Update an existing stock moviment", description = "Update an existing stock moviment by Id", tags={ "moviment" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = StockMoviment.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Item not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation exception") })
    @RequestMapping(value = "/moviment",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<StockMoviment> updateStockMoviment(@Parameter(in = ParameterIn.DEFAULT, description = "Update an existent stock moviment in the store", required=true, schema=@Schema()) @Valid @RequestBody StockMoviment body);

}

