/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.43).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ordermng.api;

import com.ordermng.api.model.Result;
import com.ordermng.api.model.StockMovement;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-07-23T12:06:14.117462+01:00[Europe/Lisbon]")
@Validated
public interface StockMovementApi {

    @Operation(summary = "Add a new stock movement to the store", description = "Add a new stock movement to the store", tags={ "stockMovement" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "405", description = "Invalid input") })
    @RequestMapping(value = "/stockMovement",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Result> addStockMovement(@Parameter(in = ParameterIn.DEFAULT, description = "Create a new stock movement in the store", required=true, schema=@Schema()) @Valid @RequestBody StockMovement body);


    @Operation(summary = "Delete an stock movement", description = "delete an stock movement", tags={ "stockMovement" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid pet value") })
    @RequestMapping(value = "/stockMovement",
        method = RequestMethod.DELETE)
    ResponseEntity<Result> deleteStockMovement(@Parameter(in = ParameterIn.HEADER, description = "Stock movement id to delete" ,required=true,schema=@Schema()) @RequestHeader(value="id", required=true) Long id);


    @Operation(summary = "List stock movement", description = "List all stock movement available", tags={ "stockMovement" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = StockMovement.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/stockMovement",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Result> listStockMovements();


    @Operation(summary = "Update an existing stock movement", description = "Update an existing stock movement", tags={ "stockMovement" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation"),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "Item not found"),
        
        @ApiResponse(responseCode = "405", description = "Validation exception") })
    @RequestMapping(value = "/stockMovement",
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Result> updateStockMovement(@Parameter(in = ParameterIn.DEFAULT, description = "Update an existent stock movement in the store", required=true, schema=@Schema()) @Valid @RequestBody StockMovement body);

}

